version: '3.7'
services:
  db:
    build:
      context: ../.
      dockerfile: ./docker/pgDockerfile
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${EXTERNAL_DB_PORT}:${DB_PORT}'
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend